import { Schema, model } from 'mongoose'
const schema = new Schema({ 
    nickname: { type: String, required: true, unique: true }, 
    date_Created: { type: Date, default: Date.now },
    data: {type:String, default: null}, //For RPGJS autogenerated JSON savefile. atm not used. 
    account_id: {type: Schema.Types.ObjectId, ref: 'Account' },
    last_login: {type:Date},
    spriteName: Schema.Types.String, //Name of Character Sprite
	imgPointer: Schema.Types.Number, //Pointer to the Sprite picture
    userType: {type: Schema.Types.String, default: 'User'} // "User" or "Admin"
})
var Character = model('Character', schema);
export default Character